#!/bin/zsh

function zgit_revision() {
    emulate -L zsh
    local branch git_dir rev

    if zgit_dir > /dev/null && git_dir=$REPLY; then
            branch=$(< $git_dir/HEAD) 2>/dev/null && \
            branch=${branch#ref: } && \
            rev=$(< $git_dir/$branch) 2>/dev/null && \
            REPLY=$rev && \
            echo "$rev" && \
            return 0
    fi
    
    REPLY=""
    return 1
}
