#!/bin/zsh

#
# See http://aperiodic.net/phil/prompt/
#

typeset -g -A -H zgit_dirs

function zgit_dir() {
    emulate -L zsh
    local dir=""
    REPLY=""

    if [[ -z $zgit_dirs[$PWD] ]]; then
      if [[ -d $PWD/.git ]]; then
        dir=$PWD/.git
      else
        dir=$(git rev-parse --git-dir) 2>/dev/null || return 1
      fi
      zrealpath $dir >/dev/null
      zgit_dirs[$PWD]=$REPLY
    else
      REPLY=$zgit_dirs[$PWD]
    fi

    echo -n -E "$REPLY"
    [[ -n $REPLY ]]
}

