#!/bin/zsh

#
# The character string printed will contain 0 or more of the
# following characters, indicating (respectively)
#
#   *    unstaged changes
#   +    staged changes
#   ?    untracked files
#   $    stashed changes
#
#
# Returns 0 for clean, 1 for dirty
#

function zgit_status {
    emulate -L zsh
    local gitstatus statstring res=0
    local git_dir=$(zgit_dir)
    
    if zgit_in_p; then
        gitstatus=$(git status 2>/dev/null)

        if [[ -z ${gitstatus:#*Changed but not updated*} ]]; then
           statstring+='*'
        fi

        if [[ -z ${gitstatus:#*Changes to be committed*} ]]; then
           statstring+='+'
        fi


        [[ -z ${gitstatus:#*Untracked files*} ]] && statstring+='?'
        [[ -f ${git_dir}/refs/stash ]] && statstring+='$'

        # set return code
        [[ -n ${gitstatus:#*nothing to commit*} ]] && res=1
    fi

    echo -nE $statstring
    return $res
}