#!/bin/zsh

typeset -g -H -A zmemcache

function zmemcache_help () {
  emulate -L zsh

  cat <<"__HELP__"
zmemcache provides an in-memory cache
__HELP__
}

function zmemcache () {
  emulate -L zsh

  local cmd="${1:-help}"
  [[ $# > 0 ]] && shift
  zmemcache_${cmd} "${(@)*}"
  return
}

