#!/bin/zsh

function zsyssourcedir {
    local droot dir
    for dir in "${(@)*}"; do
        for droot in "" "external"; do
            [[ -n "$droot" ]] && droot="${droot%/}/"
            zsourcedir "${droot}${dir}"
        done
    done
}

function zrunsystem() {
  local systemname system
  local domain="$(zdomainname)"

  for systemname in "${(@)*}"; do
    zctrace "zrunsystem: $systemname"
    system="${systemname%.d}.d"
    zsyssourcedir "$system" "$system/`uname`" "os/`uname`/$system" 
    [ -n "$domain" ] && zsyssourcedir "$system/domains/$domain" "domains/$domain/$system"
    zsyssourcedir "$system/hosts/`hostname -s`" "$system/hosts/`hostname`"
    zsyssourcedir "hosts/`hostname -s`/$system" "hosts/`hostname`/$system"
    zsyssourcedir "users/$USERNAME/$system"
  done
}
