#!/bin/zsh

zrunsystem() {
  local systemname system
  for systemname in "${(@)*}"; do
    zctrace "zrunsystem: $systemname"
    system="${systemname%.d}.d"
    zsourcedir "$system" "$system/`uname`" "os/`uname`/$system" 
    local domain="$(zdomainname)"
    [ -n "$domain" ] && zsourcedir "$system/domains/$domain"
    [ -n "$domain" ] && zsourcedir "domains/$domain/$system"
    zsourcedir "$system/hosts/`hostname -s`" "$system/hosts/`hostname`"
    zsourcedir "hosts/`hostname -s`/$system" "hosts/`hostname`/$system"
  done
}
