#!/bin/zsh

zsourcedir() {
  local dir zdir file relfile
  for dir in $*; do
    zdir=`zdirname $dir`
    zlog "zsourcedir: dir=$dir, zdir=$zdir"

    for file in $zdir/*.zsh(N); do
      relfile=${file#$ZCONFIGDIR}
      zlog "zsourcedir: file=$file relfile=$relfile"
      zsource $relfile
    done
  done
}
