#!/bin/zsh

function zsourcedir() {
  emulate zsh
  local dir zdir file relfile
  for dir in "${(@)*}"; do
    zdir=`zdirname $dir`
    zctrace "zsourcedir: dir=$dir, zdir=$zdir"

    for file in $zdir/*.zsh(N); do
      relfile=${file#$ZCONFIGDIR/}
      zctrace "zsourcedir: dir=$dir, file=$file relfile=$relfile"
      source $file
    done
  done
}
