#!/bin/zsh

ZSH_THEME=rsbox

bindkey -me 2>/dev/null

# adding c makes scrolling faster, but it always takes the
# whole screen

export LESS="efiMqR"

export IGNOREEOF=0

# export PATH=/opt/local/bin:/opt/local/sbin:$PATH
# export PATH=/usr/X11R6/bin:/usr/krb5/bin:/usr/krb5/sbin:$PATH:/usr/local/bin:/sbin:/usr/sbin:/usr/contrib/bin:/usr/local/pgsql/bin:$JAVA_HOME/bin:/usr/java/ant:/usr/local/java/jython-2.1

# 3 MB coredump limit
ulimit -c 3000

export PAGER=less
export EDITOR=vi
export BLOCKSIZE=1024
export LINES COLUMNS
export HISTSIZE=400

hd() {
hexdump -e "\"%07.7_ax  \" 16/1 \"%02x \" \"\n\"" $*
}

export PATH DISPLAY LESS TERM PS1 PS2 ignoreeof
export XDVIFONTS=/usr/local/lib/tex/fonts/cm/%f.%p

umask 022
export GROFF_TYPESETTER=ascii

export TERMCAP
export FONTS_DIR=/usr/lib/X11/misc

export LPDEST=hp1200d

# set up terminal defaults	
stty echoe susp ^z intr ^c lnext undef kill undef werase undef start undef stop undef erase '^?'

# set up completion magic
hosts=(turok test.zeevex.com prod.zeevex.com monitor.zeevex.com schultz.dreamhost.com minimus-2.local)


# ZSH options
setopt nolistbeep autolist nonomatch sh_word_split noclobber
unsetopt menucomplete

if [ "`uname -s`" = "FreeBSD" -a "$TERM" = "vt100" ]; then
	export TERM="vt100-color"
fi

if [ "$TERM" = "screen" -o "$TERM" = "vt100-color" -o "$TERM" = "vt100" ]; then
	# export TERM=vt100
	DO_COLOR=yes
fi


# if on the console, alias ls to cls (color ls)
if [ "$TERM" = "console" -o "$TERM" = "xterm" -o "X$DO_COLOR" = "Xyes" -o "$TERM" = "vt100" -o "$TERM" = "screen" -o "$TERM" = "xterm-color" ]
then
	#which colorls > /dev/null 2> /dev/null
	if [ "`uname -s`" != Linux ];  then
		alias ls='ls -G'
	else
		# GNU generation, baby
		alias ls='ls --color=auto'
	fi
fi

stty erase '^?'



# get that BASH-like "> file" behavior
noeolecho()
{
  echo -n
}
NULLCMD=noeolecho

