#!/bin/zsh


if [ -z "$_zconfig_booted" ]; then
  local zcfile
  FPATH=$ZCONFIGDIR/functions:$FPATH
  
  setopt function_argzero typeset_silent
  
  for zcfile in `find $DOTTODIR/local/build/zsh/$ZSH_VERSION -name \*.zwc 2>/dev/null `; do
      FPATH=$FPATH:$zcfile
  done

  for zcfile in $ZCONFIGDIR/functions/*; do
    autoload -Uk `basename $zcfile`
  done

  unset zcfile

  typeset -g -a zinclude_path zrequired_files
  zinclude_path=("$ZCONFIGDIR")

  # load default prefs and local prefs

  zrunsystem prefs
  source $DOTTODIR/prefs
  zsource prefs

  zrunsystem newshell
  
  _zconfig_booted=1
fi
