#!/bin/zsh

zctrace "running zprofile.."

typeset -g -x DOTTO_LOGIN_ID
[[ -z $DOTTO_LOGIN_ID ]] && DOTTO_LOGIN_ID="${TTY}:${$}:${HOST}"

# load all base functions
source $ZCONFIGDIR/core/newshell

# for Ubuntu's /etc/zsh being too clever
typeset -g skip_global_compinit=1

zrunsystem zprofile

