#!/bin/zsh

zctrace "running zprofile.."

if [ "$TERM" = "console" -o "$TERM" = "dumb" ]; then
   TERM=vt100
fi

if [ "$UID" != "0" ]; then
   # remove '.' from path
   PATH=`echo $PATH | sed -e "s/:\.//g"`
fi

export SHORTHOST=$(hostname -s)

typeset -g -x DOTTO_LOGIN_ID
[[ -z $DOTTO_LOGIN_ID ]] && DOTTO_LOGIN_ID="${TTY}:${$}:${HOST}"

# load all base functions
source $ZCONFIGDIR/core/newshell

# for Ubuntu's /etc/zsh being too clever
typeset -g skip_global_compinit=1

zrunsystem zprofile

