#!/bin/zsh
zctrace "running zshenv..."

bootzshenv() {
  if [[ $DOTTO_PROFILING == 1 ]]; then
    source $ZCONFIGDIR/core/start_profiling
  fi
  
  local dir zdir file relfile sysname
  for file in $ZCONFIGDIR/zshenv.d/*(.N) \
         $DOTTODIR/external/*/zsh/zshenv.d/*(.N) \
         $DOTTODIR/external/*/zsh/zshenv.d/`uname`/*(.N) \
         $DOTTODIR/external/*/hosts/{$SHORTHOST,$HOST}/zsh/zshenv.d/*(.N)
  do
    [[ ${file:e} == (disabled|example) ]] && continue
    source $file
  done
  
  typeset -g -a -H -U zlib_paths 
  typeset -g -a -U precmd_functions preexec_functions chpwd_functions zshexit_functions periodic_functions

  # three types of well-known function reply variables: scalar, array, and hash.
  typeset -g REPLY
  typeset -g -a reply
  typeset -g -A replyhash
  
  typeset -g -A dotto_prefs dotto_vars
  
  for dir in $DOTTODIR/local/zsh/lib(/N) $DOTTODIR/external/*/zsh/lib(/N) \
           $ZCONFIGDIR/lib(/N)
  do
    zlib_paths+=$dir
  done
}

bootzshenv
unfunction bootzshenv

typeset -g skip_global_compinit=1
