#!/bin/zsh
zctrace "running zshenv..."

bootzshenv() {
  local dir zdir file relfile sysname
  for file in $ZCONFIGDIR/zshenv.d/*(.N) \
         $ZCONFIGDIR/external/*/zsh/zshenv.d/*(.N) \
         $ZCONFIGDIR/external/*/zsh/zshenv.d/`uname`/*(.N) \
         $ZCONFIGDIR/external/*/hosts/$SHORTHOST/zshenv.d/*(.N)
  do
    [[ ${file:e} == "example" ]] && continue
    source $file
  done
  
  typeset -g -a -H -U zlib_paths 
  typeset -g -a -U precmd_functions preexec_functions chpwd_functions zshexit_functions periodic_functions
  typeset -g REPLY
  typeset -g -a reply
  
  for dir in $DOTTODIR/local/zsh/lib(/N) $DOTTODIR/external/*/zsh/lib(/N) \
           $ZCONFIGDIR/lib(/N)
  do
    zlib_paths+=$dir
  done
}

bootzshenv
unfunction bootzshenv

typeset -g skip_global_compinit=1
