#!/bin/zsh
zctrace "running zshenv..."

bootzshenv() {
  local dir zdir file relfile
  for file in $ZCONFIGDIR/zshenv.d/*(.N) \
         $ZCONFIGDIR/external/*/zsh/zshenv.d/*(.N) \
         $ZCONFIGDIR/external/*/zsh/zshenv.d/`uname`/*(.N) \
         $ZCONFIGDIR/external/*/hosts/$SHORTHOST/zshenv.d/*(.N)
  do
    [[ ${file:e} == "example" ]] && continue
    source $file
  done
}

bootzshenv
unfunction bootzshenv
