#!/bin/zsh

# Z-Shell .rc file

# $Date: 2003/03/18 07:11:02 $
# $Source: /home/rsanders/RCS/.zshrc,v $
# $Revision: 1.1 $
# $State: Exp $

# load all base functions
source $ZCONFIGDIR/core/newshell

zctrace "running zshrc.."

# set hostname
HOSTNAME=`hostname`

###
# establish a stub function to autoload functions from a file

function autoload_from
{
	local alf_file=$1
	local alf_func
	shift

	for alf_func in $*
	do
		eval "function $alf_func () { . $alf_file; $alf_func \$* }"
	done
}

zsource core/zcomp
zsource core/zperiodic 

for _zlib in $ZCONFIGDIR/lib/*(/); do
  zctrace "Loading lib $_zlib"
  if [ -d $_zlib/functions ]; then
      fpath+=$_zlib/functions
  fi
  if [ -d $_zlib/include ]; then
      zinclude_path+=$_zlib/include
  fi
  if [ -f "$_zlib/librc.zsh" ]; then
    zsource "$_zlib/librc.zsh"
  fi
done
unset _zlib _zfile

zrunsystem zshrc


