#!/bin/zsh



function zcache_command {
  emulate -L zsh
  setopt typeset_silent
  unsetopt multibyte

  local command=$1 ctype=""
  local -a args
  
  case $command in
    set|add|replace|append|prepend|cas) ctype=storage ;;
    get|gets) ctype=retrieval ;;
    stats) ctype=list ;;
    *) ctype=misc ;;
  esac
  
  case $ctype in
    storage) zcache_storage_command $* ;;
    retrieval) zcache_retrieval_command $* ;;
    list) zcache_misc_command -l $* ;;
    misc) zcache_misc_command $* ;;
    *) echo "Unknown command type: $ctype" >&2 ; return 1 ;;
  esac

  return
}