#!/bin/zsh

function zcache_disconnect {
  local fd=$1
  
  if [[ -z $fd ]]; then 
    fd=$zcache_vars[last_opened_fd]
  fi

  if [[ $zcache_vars[persistent] != 1 ]]; then
    [[ $fd == $zcache_vars[last_opened_fd] ]] && unset 'zcache_vars[last_opened_fd]'
    ztcp -c $fd
  fi
}