#!/bin/zsh


if [ -z "$_zconfig_booted" ]; then
  local zcfile
  FPATH=$ZCONFIGDIR/functions:$FPATH
  
  for zcfile in `find $ZCONFIGDIR/local/build/$ZSH_VERSION -name \*.zwc 2>/dev/null `; do
      FPATH=$FPATH:$zcfile
  done

  for zcfile in $ZCONFIGDIR/functions/*; do
    autoload -Uk `basename $zcfile`
  done

  unset zcfile

  typeset -g -a zinclude_path
  zinclude_path=("$ZCONFIGDIR")

  # load default prefs and local prefs
  # zsourcedir prefs.d prefs.d/`uname` hosts/$SHORTHOST/prefs.d
  zrunsystem prefs
  zsource prefs
  
  zrunsystem newshell
  
  _zconfig_booted=1
fi
