#!/bin/zsh

zctrace "running zprofile.."

if [ "$TERM" = "console" -o "$TERM" = "dumb" ]; then
   TERM=vt100
fi

if [ "$UID" != "0" ]; then
   # remove '.' from path
   PATH=`echo $PATH | sed -e "s/:\.//g"`
fi

pwd=`pwd`
for dir in $HOME/bin/paths/* $HOME/bin; do
    cd $dir
    realdir=`/bin/pwd -P`
    PATH=${realdir}:${PATH}
done
cd $pwd

export SHORTHOST=$(hostname -s)

# load all base functions
source $ZCONFIGDIR/core/newshell

zsourcedir $ZCONFIGDIR/zprofile.d $ZCONFIGDIR/zprofile.d/`uname` $ZCONFIGDIR/hosts/$SHORTHOST/zprofile.d

for lib in $ZCONFIGDIR/lib/*; do
  if [ -f "$lib/libprofile.zsh" ]; then
    source "$lib/libprofile.zsh"
  fi
done


