#!/bin/zsh

zctrace "running zprofile.."

if [ "$TERM" = "console" -o "$TERM" = "dumb" ]; then
   TERM=vt100
fi

if [ "$UID" != "0" ]; then
   # remove '.' from path
   PATH=`echo $PATH | sed -e "s/:\.//g"`
fi

export SHORTHOST=$(hostname -s)

# load all base functions
source $ZCONFIGDIR/core/newshell

zrunsystem zprofile

for _zlib in $ZCONFIGDIR/lib/*; do
  if [ -f "$_zlib/libprofile.zsh" ]; then
    source "$_zlib/libprofile.zsh"
  fi
done
unset _zlib


