#!/bin/zsh

# Z-Shell .rc file

# $Date: 2003/03/18 07:11:02 $
# $Source: /home/rsanders/RCS/.zshrc,v $
# $Revision: 1.1 $
# $State: Exp $

# load all base functions
source $ZCONFIGDIR/core/newshell

zctrace "running zshrc.."

# set hostname
HOSTNAME=`hostname`

###
# establish a stub function to autoload functions from a file

function autoload_from
{
	local alf_file=$1
	local alf_func
	shift

	for alf_func in $*
	do
		eval "function $alf_func () { . $alf_file; $alf_func \$* }"
	done
}

zsource core/zcomp
zsource core/zperiodic 

function {
    for zlib in $ZCONFIGDIR/lib/*; do
      if [ -f "$zlib/librc.zsh" ]; then
        source "$zlib/librc.zsh"
      fi
    done
    unset zlib
}

zsourcedir $ZCONFIGDIR/zshrc.d $ZCONFIGDIR/zshrc.d/`uname` $ZCONFIGDIR/hosts/$SHORTHOST/zshrc.d

zrunsystem zshrc


