#!/bin/zsh
# Theme with full path names and hostname
# Handy if you work on different servers all the time;

function prompt_maran_setup() {
  PROMPT='%{$fg[cyan]%}%n%{$reset_color%}@$fg[yellow]%}%M:%{$fg[green]%}%/%{$reset_color%} $(git_prompt_info) %(!.#.$) '
}