#!/bin/zsh

#
# See http://aperiodic.net/phil/prompt/
#

typeset -g -A -H zgit_dirs

function zgit_dir() {
    emulate -L zsh
    local dir

    if [ -z "$zgit_dirs[$PWD]" ]; then
        if dir="$(git rev-parse --git-dir 2> /dev/null)"; then
            [ "$dir[1]" = "/" ] || dir="${PWD}/$dir"
            zgit_dirs[$PWD]="$dir"
        fi
    fi
    
    echo -n "$zgit_dirs[$PWD]"
    [ -n "$zgit_dirs[$PWD]" ]
}

