#!/bin/zsh

function zgit_branch() {
    emulate -L zsh
    local branch git_dir

    if zgit_in_p; then
        git_dir=$(zgit_dir) && \
            branch=$(< $git_dir/HEAD) 2>/dev/null && \
            branch=${branch#ref: refs/} && \
            branch=${branch#heads/} && \
            echo "$branch" && \
            return 0
    fi
    
    return 1
        
    # if branch=$(git symbolic-ref HEAD 2>/dev/null); then
    #     echo "${branch#refs/heads/}"
    # else
    #     return 1
    # fi
}
