#!/bin/zsh

function zgit_revision() {
    emulate -L zsh
    local branch git_dir rev

    if zgit_in_p; then
        git_dir=$(zgit_dir)
        branch=$(< $git_dir/HEAD)
        branch=${branch#ref: }
        rev=$(< $git_dir/$branch)
        echo "$rev"
    else
        return 1
    fi
}
