#!/bin/zsh

#
# See http://aperiodic.net/phil/prompt/
#

typeset -g -A -H zgit_dirs

function zgit_dir() {
    if [ -z "$zgit_dirs[$PWD]" ]; then
        zgit_dirs[$PWD]="$(git rev-parse --git-dir 2> /dev/null)"
    fi
    echo "$zgit_dirs[$PWD]"
}

