#!/bin/zsh

function zgit_branch() {
    emulate -L zsh
    local branch

    # local output
    # output=$(git branch 2>/dev/null)
    # if [ $? = 0 ]; then
    #     local -a lines
    #     set -A lines "${(f)output}"
    #     branch="${lines[(r)\**]#\* }"
    #     echo "$branch"
    # else
    #     return 1
    # fi
    
    if branch=$(git symbolic-ref HEAD 2>/dev/null); then
        echo "${branch#refs/heads/}"
    else
        return 1
    fi
}
