#!/bin/zsh

#
# See http://aperiodic.net/phil/prompt/
#

function zgit_vcs_info {
    emulate -L zsh
    local output branch
    output=$(git branch 2>/dev/null)
    if [ $? = 0 ]; then
        local -a lines
        set -A lines "${(f)output}"
        branch="${lines[(r)\**]#\* }"
        vcs_info_msg_0_="(git [$branch])"
    else
        vcs_info_msg_0_=""
    fi
}


function old_box_prompt_info() {
  local CURRENT_BRANCH
  if [[ -d .git ]]; then
    local ref=$(git symbolic-ref HEAD 2> /dev/null) || return
    local branch=${ref#refs/heads/}
    CURRENT_BRANCH="git:($PR_MAGENTA${branch}$PR_YELLOW)$PR_NO_COLOUR$(parse_git_dirty)"
  else
    CURRENT_BRANCH='%D{%a,%b%d}'
  fi

  echo $CURRENT_BRANCH
}


function zgit_box_prompt_info() {
  if [ -n "$vcs_info_msg_0_" ]; then
    # CURRENT_BRANCH="git:($PR_MAGENTA${branch}$PR_YELLOW)$PR_NO_COLOUR$(parse_git_dirty)"
    CURRENT_BRANCH="$vcs_info_msg_0_"
  else
    # CURRENT_BRANCH="($PR_YELLOW%D{%a,%b%d}$PR_BLUE)"
    CURRENT_BRANCH=""
  fi

  echo $CURRENT_BRANCH
}


function zgit_parse_dirty () {
  [[ $(git status | tail -n1) != "nothing to commit (working directory clean)" ]] && echo " %{$fg[yellow]%}x$PR_NO_COLOUR"
}

