#!/bin/zsh

function display_dimensions() {
  emulate -L zsh

  local string="$1" width=${2:-$COLUMNS}
  typeset -L -i 10 lines=0
  
  local -E divisor=0.0
  local -E split=0.0 rem=0.0
  
  (( divisor = ${COLUMNS} + 0.0 ))
  
  for line in "${(f)string}"; do
      (( split = $#line / $divisor ))
      (( rem = $#line % $divisor ))
      (( lines = lines + $split ))
      if [[ "$rem" -gt 0 ]]; then
          (( lines = lines + 1 ))
      fi
  done
  
  REPLY=$lines
  printf "%d\n" "$lines"
}

# typeset -g COLUMNS=20
# 
# display_dimensions "dfdsjkhfdkjfhadsklfhdaljfhdaslkfhdaslkfhjdasklfjhdlaskfhdsalkfhjdas"
# display_dimensions "a
# b
# c
# d"
# display_dimensions "abcdefghijklmnopqrstuvwxyz
# c
# d"
# display_dimensions "abcdefghijklmno
# c
# d"
# display_dimensions "abcde"