#!/bin/zsh

typeset -g DOTTO_VERSION

function dotto_version {
  emulate -L zsh
  local ver description tag  

  [[ -z $dotto_vars[version] && -n $DOTTO_VERSION ]] && dotto_vars[version]=$DOTTO_VERSION

  if [[ -z $dotto_vars[version] ]]; then
    local oldpwd=$PWD
  
    {
      uselib zgit
      cd $DOTTODIR
  
      if zgit_in_p; then
        tag=$(git describe --tags HEAD 2>/dev/null)
        description=$(git describe --all HEAD 2>/dev/null)
        [[ -n "$tag" ]] && ver="$tag "
        if [[ $description != */$tag ]]; then
          local pats pat
          pats=("refs/heads/" "refs/tags/" "tags/" "heads/")
          for pat in $pats; do
            description=${description#${pat}}
          done
          [[ -n $description && $description != $tag ]] & ver+="($description) "
        fi
      else
        ver=""
      fi
  
    } always {
      cd $oldpwd
    }

    dotto_vars[version]="$(ztrim $ver)"
  fi
  
  export DOTTO_VERSION=$dotto_vars[version]
  REPLY=$DOTTO_VERSION
  echo $DOTTO_VERSION
  [[ -n $DOTTO_VERSION ]]
}