#!/bin/zsh

function newer_than {
  emulate -L zsh
  local basetime=${1} file
  shift
  
  for file in "${(@)*}"; do
    if [[ -e $file && $(builtin stat +mtime "$file") -gt $basetime ]]; then
        return 0
    fi
  done
  return 1
}