#!/bin/zsh

# strip \r\n from end of a string

function zchomp {
  emulate -L zsh
  
  local str=${1:-$REPLY} chr=""

  chr=10
  [[ $str[-1] == ${(#)chr} ]] && str[-1]=""
  chr=13
  [[ $str[-1] == ${(#)chr} ]] && str[-1]=""
  REPLY=$str
}