#!/bin/zsh

function zrealpath() {
  emulate -L zsh

  local chpwd_functions
  unset chpwd_functions

  local pth="$1" dir="" 
  REPLY=""

  [[ $pth[1] == "/" ]] || pth="$PWD/$pth"

  if [ "${pth:t}" = "." -o "${pth:t}" = ".." -o -d "$pth" ]; then
    REPLY=$(cd -P "$pth" && pwd -P)
  elif [[ "${pth:h}" == "/" ]]; then
    REPLY="$pth"
  else
    dir=${pth:h}
    dir=$(cd -P "$dir" && pwd -P)
  
    REPLY="$dir/${pth:t}"
  fi
  
  echo $REPLY
}