#!/bin/zsh

function zrealpath() {
  emulate -L zsh

  local chpwd_functions
  unset chpwd_functions

  local pth="$1" dir="" 
  
  [[ $pth[1] == "/" ]] || pth="$PWD/$pth"

  if [ "${pth:t}" = "." -o "${pth:t}" = ".." -o -d "$pth" ]; then
      (cd -P "$pth" && pwd -P)
      return
  fi

  if [[ "${pth:h}" == "/" ]]; then
      echo "$pth"
      return
  fi
  
  dir=${pth:h}
  dir=$(cd -P "$dir" && pwd -P)
  
  echo "$dir/${pth:t}"
}