#!/bin/zsh

function zsyssourcedir {
    emulate zsh
    local droot dir
    local -a droots
    
    droots=("")
    for droot in $DOTTODIR/external/*(N); do
        droots+=${droot#$ZCONFIGDIR/}/zsh
        droots+=${droot#$ZCONFIGDIR/}
    done
    
    for dir in "${(@)*}"; do
        for droot in "${(@)droots}"; do
            [[ -n "$droot" ]] && droot="${droot%/}/"
            zsourcedir "${droot}${dir}"
        done
    done
}

function zrunsystem() {
  emulate zsh
  local systemname system
  local domain="$(zdomainname)"

  local sysuser=${ZSH_PREFS_USER:-$USERNAME}

  for systemname in "${(@)*}"; do
    zctrace "zrunsystem: $systemname"
    system="${systemname%.d}.d"
    
    typeset -a dirs
    
    dirs+="$system" 
    dirs+="$system/`uname`" 
    dirs+="os/`uname`/zsh/$system" 
    [ -n "$domain" ] && dirs+="domains/$domain/zsh/$system"
    dirs+="hosts/`hostname -s`/zsh/$system" 
    dirs+="hosts/`hostname`/zsh/$system"
    dirs+="users/$USERNAME/zsh/$system"
    
    zsyssourcedir $dirs
  done
}
