#!/bin/zsh

#
# Return true if either an alias, a shell function, or an autoload
# is defined
#

function zshellfunc_exists {
  emulate -L zsh
  local name=$1 ftype
  
  [[ -n $functions[$name] ]] && return 0
  [[ -n $aliases[$name] ]] && return 0
  return 1
}