#!/bin/zsh

function zsourcedir() {
  local dir zdir file relfile component systemname
  
  if [[ $1 == "-s" ]]; then
    systemname=$2
    shift 2
  fi

  local -a pats
  for dir in "${(@)*}"; do
    [[ -d $dir ]] && pats+="${dir}/*.zsh(N)"
  done

  for file in ${(@)~pats}; do
    # zctrace "zsourcedir: file=$file, zdir=$zdir"

    component=${file:t}
    component=${component:r}
    
    # strip off any cron-style 00 or A00 prefixes, used to provide a natural
    # ordering
    component=${component#[A-Z][0-9][0-9]}
    component=${component#[0-9][0-9]}
    
    [[ -n ${dotto_disabled_components[(r)$component]} ]] && continue
    [[ -n ${dotto_disabled_components[(r)${systemname}/${component}]} ]] && continue
    
    source $file
  done

}
