#!/bin/zsh

function zsource() {
  emulate zsh
  local arg
  for arg in "${(@)*}"; do
    arg=${arg#$ZCONFIGDIR/}
    if [[ $arg == *.zwc || -z $arg ]]; then
      zlog "skipping zwc file: $arg"
      continue
    fi
    
    if [[ -f "$ZCONFIGDIR/$arg" ]]; then
      source "$ZCONFIGDIR/$arg"
      zlog "zsource: sourcing zconfigdir/$arg"
    elif [[ -f "$DOTTODIR/$arg" ]]; then
      source "$DOTTODIR/$arg"
      zlog "zsource: sourcing dottodir/$arg"
    fi
    if [[ -f "$DOTTODIR/local/zsh/$arg" ]]; then
      source "$DOTTODIR/local/zsh/$arg"
      zlog "zsource: sourcing dottodir/local/zsh/$arg"
    fi
  done
}
