#!/bin/zsh

function prompt_geoffgarside_setup() {
  # PROMPT="[%*] %n:%c $(git_prompt_info)%(!.#.$) "
  PROMPT='[%*] %{$fg[cyan]%}%n%{$reset_color%}:%{$fg[green]%}%c%{$reset_color%}$(git_prompt_info) %(!.#.$) '
}
