#!/bin/zsh

# Found on the ZshWiki
#  http://zshwiki.org/home/config/prompt
#

function prompt_example_setup() {
  PROMPT="%{$fg[red]%}%n%{$reset_color%}@%{$fg[blue]%}%m %{$fg[yellow]%}%~ %{$reset_color%}%% "
}