#!/bin/zsh


function run_periodic_dir() {
    emulate -L zsh
    local last dir seconds key
    
    dir=$1
    local per=$2
    key="PERIODIC_DIR_$dir"

    last=$ZCRON_TIMESTAMPS[$key]
    
    if [[ $last != <-> ]]; then
         last=0
    fi

    if [[ $((SECONDS - last)) -gt $per ]]; then
        ZCRON_TIMESTAMPS[$key]=$SECONDS
        zsourcedir $ZCONFIGDIR/$dir
    fi
}
