#!/bin/zsh

function zcron {
  emulate -L zsh
  setopt typeset_silent
  
  local opt="" OPTIND="" OPTARG="" retval=0
  local cmd="" period="" fun=""

  # the verb can precede the first option, or be after all options
  if [[ -n $1 && ! $1 == -* ]]; then
    cmd=$1
    shift
  fi
  
  while getopts "c:hf:dlat:" opt; do
    case "$opt" in
      c) cmd=$OPTARG ;;
      f) fun=$OPTARG ;;
      d) cmd=delete ;;
      l) cmd=list ;;
      a) cmd=add ;;
      t) period=$OPTARG ;;
      *) echo -E "Unknown option: $opt" >&2; return 1;;
    esac
  done
  
  shift $(( OPTIND - 1 ))
  
  [[ -z $cmd ]] && { cmd=$1; shift }

  case $cmd in
    add) 
      [[ -z $period ]] && { period=$1; shift }
      [[ -z $fun ]] && { fun=$1; shift }
      zcron_add $period $fun
    ;;

    list) 
      zcron_list $*
    ;;

    delete) 
      [[ -z $fun ]] && { fun=$1; shift }
      zcron_delete $period $fun    
    ;;
    
    *) echo -E "Unknown cron command: $opt" >&2; return 1;;
  esac
}