#!/usr/bin/env zsh


emulate -L zsh
unsetopt warn_create_global

APPS=(irb lftp ncftp screen ssh tmux vim emacs)

function safecp {
  yes n | cp -i "${(@)*}"
}


function work_in_dir {
  local dir=$1
  { mkdir -p $dir && cd $dir } || { echo "Cannot create directory $dir"; exit 2 }
}


[[ -z $DOTTODIR || ! -d $DOTTODIR/external ]] && { echo "Dotto not installed"; exit 1 }

name=${1:-$USERNAME}
dir=$DOTTODIR/external/$name

[[ -d $dir ]] && { echo "$dir already exists"; exit 1 }

work_in_dir $dir
cat > README <<README_CONTENTS
This directory was automatically generated by Dotto.  Use it to contain your
personal configuration preferences and code.

Rename prefs.example to prefs, and edit it to suit you.

See http://github.com/rsanders/dotto for more information.
README_CONTENTS

[[ -f $DOTTODIR/prefs.example ]] && safecp $DOTTODIR/prefs.example $dir

# create zsh framework
zshdir=$dir/zsh

work_in_dir $zshdir


for subdir in "." "hosts/${HOST}" "os/$(uname)" "users/${USERNAME}"; do
  work_in_dir $dir/$subdir

  for system in zshenv zlogin zprofile zshrc newshell zcomp zperiodic zlogout; do
    mkdir -p "zsh/${system}.d"
  done
  mkdir -p "zsh/lib" "zsh/functions"
  
  mkdir -p "conf.d"
  
  work_in_dir apps
  
  for app in $APPS; do
    mkdir -p $app
  done
done

echo "Dotto configuration directory $dir created"
